# -*- coding: UTF-8 -*-
"""
Django settings for hellowrld project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
from datetime import timedelta

import environ

PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
SITE_NAME = os.path.basename(PROJECT_ROOT)
BASE_DIR = os.path.dirname(PROJECT_ROOT)

env = environ.Env(
    DEBUG=(bool, False),
    SECRET_KEY=(str, "addSecretKeyToEnvironment"),
    DJANGO_LOG_LEVEL=(str, 'WARNING'),
    ELASTIC_HOST=(str, ''),
    GITHUB_API_USER=(str, ''),
    GITHUB_API_TOKEN=(str, ''),
    GITHUB_WEBHOOK_SECRET=(str, ''),
    CELERY_BROKER_URL=(str, ''),
    RECAPTCHA_PUBLIC_KEY=(str, ''),
    RECAPTCHA_PRIVATE_KEY=(str, ''),
)
environ.Env.read_env(env_file=os.path.join(BASE_DIR, '.env'))

PAGE_URL = env('PAGE_URL')

SECRET_KEY = env('SECRET_KEY')

DEBUG = env.bool('DEBUG')

ALLOWED_HOSTS = [
    '.haindex.ix-dev.eu',
    '.home.schoenbuchallee.de',
]

# Application definition

INSTALLED_APPS = [
    # django apps here
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.flatpages',

    # own apps here
    'haindex.apps.HAIndexConfig',

    # 3rd party apps here
    'django_elasticsearch_dsl',
    'bootstrap3',
    'django_extensions',
    'django_celery_results',
    'django_celery_beat',
    'snowpenguin.django.recaptcha2',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'haindex.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'haindex.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases
if 'TRAVIS' in os.environ:
    DATABASES = {
        'default': {
            'ENGINE':   'django.db.backends.postgresql_psycopg2',
            'NAME':     'travisci',
            'USER':     'postgres',
            'PASSWORD': '',
            'HOST':     'localhost',
            'PORT':     '',
        }
    }
else:
    DATABASES = {'default': env.db()}

# Logging

LOGGING_DEFAULT_HANDLERS = ['console']
LOGGING_LOG_LEVEL = env('DJANGO_LOG_LEVEL')
LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,
    'formatters': {
        'standard': {
            'format': "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
            'datefmt': "%d/%b/%Y %H:%M:%S"
        },
        'verbose': {
            'format': '%(asctime)s %(levelname)s %(name)s %(filename)s:%(lineno)d %(funcName)s %(process)d '
                      '%(thread)d %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': LOGGING_DEFAULT_HANDLERS,
            'level': LOGGING_LOG_LEVEL,
            'formatter': 'standard',
        },
        'django.db.backends': {
            'handlers': LOGGING_DEFAULT_HANDLERS,
            'level': LOGGING_LOG_LEVEL,
            'propagate': False,
        },
        'celery': {
            'handlers': LOGGING_DEFAULT_HANDLERS,
            'level': LOGGING_LOG_LEVEL,
            'propagate': False,
        },
    },
}

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
LANGUAGES = (
    ('en', 'English'),
)

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(PROJECT_ROOT, 'staticfiles')
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'haindex', 'static'),
)

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

SITE_ID = 1

# elastic search

ELASTICSEARCH_DSL={
    'default': {
        'hosts': env('ELASTIC_HOST'),
    },
}

# app related

CELERY_BROKER_URL = env('CELERY_BROKER_URL')
CELERY_HIJACK_ROOT_LOGGER = False
CELERY_QUEUE_HA_POLICY = 'all'
CELERY_WORKER_DIRECT = False
CELERY_RESULT_BACKEND = 'django-db'
CELERY_RESULT_PERSISTENT = True
CELERY_IGNORE_RESULT = True
CELERY_TASK_RESULT_EXPIRES = timedelta(days=7)
CELERY_TIMEZONE = TIME_ZONE
CELERY_TRACK_STARTED = True
CELERY_SEND_EVENTS = False
CELERY_SEND_TASK_SENT_EVENT = False
CELERY_EVENT_QUEUE_TTL = 60

LOGIN_URL = '/admin/'

SESSION_SERIALIZER = 'django.contrib.sessions.serializers.PickleSerializer'

BOOTSTRAP3 = {'horizontal_label_class': 'col-md-2', 'horizontal_field_class': 'col-md-10', 'success_css_class': ''}

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

GITHUB_API_USER = env('GITHUB_API_USER')
GITHUB_API_TOKEN = env('GITHUB_API_TOKEN')
GITHUB_WEBHOOK_SECRET = env('GITHUB_WEBHOOK_SECRET')

RECAPTCHA_PUBLIC_KEY = env('RECAPTCHA_PUBLIC_KEY')
RECAPTCHA_PRIVATE_KEY = env('RECAPTCHA_PRIVATE_KEY')
