# Generated by Django 2.1.7 on 2019-03-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haindex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'User'), (2, 'Organization')], default=1, verbose_name='User type'),
        ),
    ]
