# Generated by Django 2.1.7 on 2019-02-19 09:10

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('haindex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('tag_name', models.CharField(max_length=50, verbose_name='Tag name')),
                ('body', models.TextField(verbose_name='Body')),
                ('published_at', models.DateTimeField(verbose_name='Published at')),
                ('zipball_url', models.URLField(verbose_name='Zipball URL')),
            ],
            options={
                'verbose_name': 'Repository release',
                'ordering': ('repository', '-published_at'),
                'verbose_name_plural': 'Repository releases',
            },
        ),
        migrations.AddField(
            model_name='repository',
            name='has_package_file',
            field=models.BooleanField(default=False, verbose_name='Contains a package.yaml'),
        ),
        migrations.AddField(
            model_name='repositoryrelease',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haindex.Repository', verbose_name='Repository'),
        ),
        migrations.AlterUniqueTogether(
            name='repositoryrelease',
            unique_together={('repository', 'tag_name')},
        ),
    ]
